const rawData=window.ONANEM_DATA||[], $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const uniq=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ca'));
const asArray=v=>Array.isArray(v)?v:(v?[v]:[]);
const clamp5=n=>Math.max(0,Math.min(5,Number(n)||0));
const data=rawData.map(p=>({
  estat:'actiu', categories:[], imatges:[], recomanacions:[], visites:[], ...p,
  categories:asArray(p.categories?.length?p.categories:[...(p.cuines||[]),...(p.especialitats||[])]),
  imatges:asArray(p.imatges), recomanacions:asArray(p.recomanacions), visites:asArray(p.visites)
}));
let current='restaurant', filters={region:'',zone:'',cuisine:'',specialty:'',status:'actiu'};
const labels={restaurant:['Restaurants','On menjar'],recepta:['Receptes','Què cuinar'],botiga:['Botigues','On comprar'],experiencia:['Experiències','Què descobrir'],vi:['Vins','Denominacions d’origen catalanes']};
const icons={restaurant:'🍴',botiga:'🛍️',experiencia:'✨',recepta:'👨‍🍳',vi:'🍷'};
const wineDOs=['DO Alella','DO Catalunya','DO Cava','DO Conca de Barberà','DO Costers del Segre','DO Empordà','DO Montsant','DO Penedès','DO Pla de Bages','DOQ Priorat','DO Tarragona','DO Terra Alta'];
const statusInfo={
  actiu:{label:'Actiu',icon:'🟢'},
  temporal:{label:'Tancat temporalment',icon:'🟡'},
  tancat:{label:'Tancat definitivament',icon:'🔴'}
};
function getStatus(p){return statusInfo[p.estat]||statusInfo.actiu}
function loc(p){if(p.tipus==='recepta')return [p.categoria,p.tipusAliment].filter(Boolean).join(' · ');return [p.zona,p.vegueria&&p.vegueria!=='...Altres'?p.vegueria:p.pais].filter(Boolean).join(' · ')}
function searchable(p){return norm([p.nom,p.zona,p.vegueria,p.pais,p.adreca,p.notes,p.rang,p.recomanatPer,p.categoria,p.tipusAliment,p.cuiner,p.cuina,p.dificultat,p.ingredients,p.preparacio,p.narracio,p.estat,...asArray(p.categories),...asArray(p.allergens),...asArray(p.cuines),...asArray(p.especialitats),...asArray(p.serveis),...asArray(p.recomanacions).flatMap(r=>[r.nom,r.comentari])].join(' '))}
function moduleData(type){return data.filter(x=>x.tipus===type)}
function counts(){$('#countRestaurant').textContent=moduleData('restaurant').length;$('#countRecepta').textContent=moduleData('recepta').length;$('#countBotiga').textContent=moduleData('botiga').length;$('#countExperiencia').textContent=moduleData('experiencia').length}
function statusBadge(p){const s=getStatus(p);return p.estat&&p.estat!=='actiu'?`<span class="status-badge status-${esc(p.estat)}">${s.icon} ${s.label}</span>`:''}
function globalSearch(q){const area=$('#globalArea'),out=$('#globalResults');if(!q.trim()){area.classList.add('hidden');out.innerHTML='';return}const nq=norm(q),types=['restaurant','recepta','botiga','experiencia'];const groups=types.map(type=>[type,moduleData(type).filter(p=>searchable(p).includes(nq))]).filter(([,x])=>x.length);const total=groups.reduce((n,[,x])=>n+x.length,0);area.classList.remove('hidden');$('#globalCount').textContent=`${total} resultats`;out.innerHTML=groups.length?groups.map(([type,list])=>`<section class="group"><h3>${icons[type]} ${labels[type][0]} (${list.length})</h3>${list.slice(0,6).map(resultCard).join('')}${list.length>6?`<button class="open" data-more="${type}">Veure'n ${list.length} →</button>`:''}</section>`).join(''):`<div class="empty">No hi ha cap coincidència a les dades importades.</div>`;bindOpen();$$('[data-more]').forEach(b=>b.onclick=()=>openModule(b.dataset.more,q))}
function resultCard(p){const img=p.imatge||p.logo||p.imatges?.[0]||'';return `<article class="result-card" data-open="${esc(p.id)}"><div class="thumb" style="${img?`background-image:url('${esc(img)}')`:''}"></div><div class="result-info"><b>${esc(p.nom)}</b><small>${esc(loc(p))}</small>${statusBadge(p)}<span class="kind">${icons[p.tipus]} ${esc(labels[p.tipus]?.[0]||p.tipus)}</span></div></article>`}
function recipeFilters(arr){$('#regionLabel').textContent='Categoria';$('#zoneLabel').textContent='Tipus d’aliment';$('#cuisineLabel').textContent='Cuiner';$('#specialtyLabel').textContent='Dificultat';fill('#region',uniq(arr.map(p=>p.categoria)),filters.region);fill('#zone',uniq(arr.map(p=>p.tipusAliment)),filters.zone);fill('#cuisine',uniq(arr.map(p=>p.cuiner)),filters.cuisine);fill('#specialty',uniq(arr.map(p=>p.dificultat)),filters.specialty)}
function standardFilters(arr){$('#regionLabel').textContent=current==='restaurant'?'Vegueria':'Territori';$('#zoneLabel').textContent='Zona';$('#cuisineLabel').textContent='Cuina';$('#specialtyLabel').textContent=current==='restaurant'?'Categoria / especialitat':'Tipus / especialitat';const r=uniq(arr.map(p=>p.territori==='altres'?p.pais:p.vegueria));fill('#region',r,filters.region);const zarr=filters.region?arr.filter(p=>(p.territori==='altres'?p.pais:p.vegueria)===filters.region):arr;fill('#zone',uniq(zarr.map(p=>p.zona)),filters.zone);fill('#cuisine',uniq(arr.flatMap(p=>p.cuines||[])),filters.cuisine);fill('#specialty',uniq(arr.flatMap(p=>p.categories?.length?p.categories:(p.especialitats||[]))),filters.specialty)}
function populateFilters(){const arr=moduleData(current);current==='recepta'?recipeFilters(arr):standardFilters(arr);$('#cuisineField').classList.toggle('hidden',!['restaurant','recepta'].includes(current));$('#statusField').classList.toggle('hidden',!['restaurant','botiga','experiencia'].includes(current));$('#status').value=filters.status}
function fill(id,vals,val){$(id).innerHTML='<option value="">Totes</option>'+vals.map(v=>`<option ${v===val?'selected':''}>${esc(v)}</option>`).join('')}
function filtered(q=''){const nq=norm(q);return moduleData(current).filter(p=>{const statusOk=current==='recepta'||!filters.status||(filters.status==='tots'?true:p.estat===filters.status);const ok=current==='recepta'?(!filters.region||p.categoria===filters.region)&&(!filters.zone||p.tipusAliment===filters.zone)&&(!filters.cuisine||p.cuiner===filters.cuisine)&&(!filters.specialty||p.dificultat===filters.specialty):(!filters.region||(p.territori==='altres'?p.pais:p.vegueria)===filters.region)&&(!filters.zone||p.zona===filters.zone)&&(!filters.cuisine||(p.cuines||[]).includes(filters.cuisine))&&(!filters.specialty||(p.categories||[]).includes(filters.specialty));return statusOk&&ok&&(!nq||searchable(p).includes(nq))})}
function openModule(type,q=''){if(type==='vi'){openWineModule();return}current=type;filters={region:'',zone:'',cuisine:'',specialty:'',status:type==='recepta'?'tots':'actiu'};$('#home').classList.add('hidden');$('#moduleView').classList.remove('hidden');$('#moduleTitle').textContent=labels[type][0];$('#moduleSubtitle').textContent=labels[type][1];$('#filterBtn').classList.remove('hidden');populateFilters();renderModule(q);window.scrollTo({top:0,behavior:'smooth'})}
function openWineModule(){current='vi';$('#home').classList.add('hidden');$('#moduleView').classList.remove('hidden');$('#moduleTitle').textContent='Vins';$('#moduleSubtitle').textContent='Estructura inicial per denominacions d’origen';$('#filterBtn').classList.add('hidden');$('#cards').innerHTML=`<section class="wine-intro"><h3>🍷 Vins catalans</h3><p>Aquest mòdul quedarà organitzat per denominació d’origen. Els vins tindran vida pròpia i les relacions amb restaurants o receptes seran sempre opcionals.</p><div class="do-grid">${wineDOs.map(x=>`<div class="do-pill">${esc(x)}</div>`).join('')}</div></section>`;window.scrollTo({top:0,behavior:'smooth'})}
function renderModule(q=''){const list=filtered(q);$('#moduleSubtitle').textContent=`${labels[current][1]} · ${list.length} resultats`;$('#cards').innerHTML=list.length?list.map(card).join(''):`<div class="empty">No hi ha resultats amb aquesta combinació.</div>`;bindOpen()}
function card(p){const img=p.imatge||p.logo||p.imatges?.[0]||'',meta=p.tipus==='recepta'?[p.cuiner,p.dificultat,p.temps?`${p.temps} min`:null].filter(Boolean).join(' · '):[...(p.cuines||[]),...(p.categories||[])].slice(0,3).join(' · ')||p.notes||'';return `<article class="card clickable-card ${p.estat!=='actiu'?'closed-card':''}" data-open="${esc(p.id)}" role="button" tabindex="0" aria-label="Obrir la fitxa de ${esc(p.nom)}"><div class="photo" style="${img?`background-image:url('${esc(img)}')`:''}"></div><div class="body"><h3>${esc(p.nom)}</h3><div class="loc">${p.tipus==='recepta'?'🍽️':'📍'} ${esc(loc(p))}</div>${statusBadge(p)}<div class="meta">${esc(meta)}</div></div></article>`}
function bindOpen(){$$('[data-open]').forEach(el=>{const open=()=>showDetail(data.find(x=>x.id===el.dataset.open));el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function stars(n){const v=clamp5(n);return `<span class="stars" aria-label="${v} de 5">${'★'.repeat(Math.round(v))}${'☆'.repeat(5-Math.round(v))}</span><b>${v?v.toFixed(1).replace('.',','):''}</b>`}
function allRatings(p){const own=p.valoracio?[{nom:'La meva valoració',...p.valoracio,propia:true}]:[];return [...own,...asArray(p.recomanacions)]}
function averageRatings(p){const rs=allRatings(p);const keys=['menjar','servei','local','preu'];const avg={};keys.forEach(k=>{const vals=rs.map(r=>Number(r[k])).filter(v=>v>0);avg[k]=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0});const all=keys.flatMap(k=>rs.map(r=>Number(r[k])).filter(v=>v>0));avg.general=all.length?all.reduce((a,b)=>a+b,0)/all.length:0;const tornaria=rs.map(r=>r.tornaria).filter(Boolean);avg.tornaria=tornaria.length?Math.round(tornaria.filter(x=>x==='segur'||x===true).length/tornaria.length*100):null;return avg}
function ratingSummary(p){const rs=allRatings(p);if(!rs.length)return '';const a=averageRatings(p);return `<section class="detail-section"><h3>Valoracions</h3><div class="rating-summary"><div class="rating-main"><span>Mitjana</span>${stars(a.general)}<small>${rs.length} ${rs.length===1?'valoració':'valoracions'}</small></div><div class="rating-grid">${[['🍽️','Menjar','menjar'],['😊','Servei','servei'],['🏠','Local','local'],['💰','Qualitat-preu','preu']].map(([i,l,k])=>a[k]?`<div><span>${i} ${l}</span>${stars(a[k])}</div>`:'').join('')}</div>${a.tornaria!==null?`<div class="return-rate">❤️ El ${a.tornaria}% hi tornaria segur.</div>`:''}</div>${rs.map(r=>ratingEntry(r)).join('')}</section>`}
function ratingEntry(r){return `<article class="rating-entry"><div class="rating-head"><div><b>${esc(r.nom||'Valoració')}</b>${r.data?`<small>${esc(r.data)}</small>`:''}</div>${r.propia?'<span class="own-tag">Personal</span>':''}</div><div class="mini-ratings">${[['Menjar','menjar'],['Servei','servei'],['Local','local'],['Preu','preu']].map(([l,k])=>r[k]?`<span>${l}: ${stars(r[k])}</span>`:'').join('')}</div>${r.tornaria?`<div class="would-return">❤️ ${r.tornaria==='segur'?'Hi tornaria segur':r.tornaria==='sense_pressa'?'Hi tornaria, però sense pressa':'No hi tornaria'}</div>`:''}${r.comentari?`<p>${esc(r.comentari)}</p>`:''}</article>`}
function statusNotice(p){if(!p.estat||p.estat==='actiu')return '';const s=getStatus(p);return `<div class="status-notice status-${esc(p.estat)}"><b>${s.icon} ${s.label}</b>${p.dataBaixa?`<span>Des de ${esc(p.dataBaixa)}</span>`:''}${p.motiuBaixa?`<p>${esc(p.motiuBaixa)}</p>`:''}<small>La fitxa es conserva com a part de la biblioteca personal.</small></div>`}
function gallery(p){const imgs=uniq([p.imatge,...asArray(p.imatges)].filter(Boolean));if(imgs.length<=1)return '';return `<section class="detail-section"><h3>Galeria</h3><div class="gallery">${imgs.slice(1).map(x=>`<img src="${esc(x)}" alt="Fotografia de ${esc(p.nom)}" loading="lazy">`).join('')}</div></section>`}
function visits(p){if(!p.visites?.length)return '';return `<section class="detail-section"><h3>Visites</h3>${p.visites.map(v=>`<article class="visit"><b>${esc(v.data||'Visita')}</b>${v.ambQui?`<span>👥 ${esc(v.ambQui)}</span>`:''}${v.motiu?`<span>🎉 ${esc(v.motiu)}</span>`:''}${v.preuPersona?`<span>💶 ${esc(v.preuPersona)} € per persona</span>`:''}${v.comentari?`<p>${esc(v.comentari)}</p>`:''}</article>`).join('')}</section>`}
function showRecipe(p){const stats=[p.comensals?`👥 ${p.comensals} racions`:'',p.temps?`⏱️ ${p.temps} min`:'',p.coccio?`🔥 ${p.coccio} min cocció`:'',p.dificultat?`${p.dificultat==='Fàcil'?'💚':p.dificultat==='Mitjana'?'💜':'❤️'} ${p.dificultat}`:'',p.saludable==='✅'?'🥗 Saludable':''].filter(Boolean);return `<div class="eyebrow">👨‍🍳 Recepta · ${esc(p.categoria)}</div><h2>${esc(p.nom)}</h2><div class="loc">${esc([p.tipusAliment,p.cuina,p.cuiner&&`de ${p.cuiner}`].filter(Boolean).join(' · '))}</div><div class="recipe-stats">${stats.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>${p.narracio?`<div class="narrative">${esc(p.narracio)}</div>`:''}${p.restaurantRelacionat?`<div class="info"><small>Restaurant relacionat</small>🍴 ${esc(p.restaurantRelacionat)}</div>`:''}${p.ingredients?`<section class="detail-section"><h3>Ingredients</h3><div class="detail-text">${esc(p.ingredients)}</div></section>`:''}${p.preparacio?`<section class="detail-section"><h3>Preparació</h3><div class="detail-text">${esc(p.preparacio)}</div></section>`:''}${p.variacions?`<section class="detail-section"><h3>Variacions</h3><div class="detail-text">${esc(p.variacions)}</div></section>`:''}${p.allergens?.length?`<section class="detail-section"><h3>Al·lèrgens</h3><div class="recipe-stats">${p.allergens.map(x=>`<span class="chip">⚠️ ${esc(x)}</span>`).join('')}</div></section>`:''}${p.observacions?`<section class="detail-section"><h3>Observacions</h3><div class="detail-text">${esc(p.observacions)}</div></section>`:''}${p.enllac?`<a class="external-link" href="${esc(p.enllac)}" target="_blank" rel="noopener">Obrir l’enllaç ↗</a>`:''}`}
function safeUrl(url){const v=String(url||'').trim();if(!v)return '';return /^(https?:|mailto:|tel:)/i.test(v)?v:`https://${v}`}
function cleanPhone(v){return String(v||'').replace(/\.0$/,'').replace(/[^+\d]/g,'')}
function actionLinks(p){const phone=cleanPhone(p.telefon1),wa=cleanPhone(p.whatsapp||p.telefon1);const links=[
  phone&&['📞','Trucar',`tel:${phone}`],wa&&['💬','WhatsApp',`https://wa.me/${wa.replace(/^00/,'').replace(/^\+/,'')}`],
  p.web&&['🌐','Web',safeUrl(p.web)],p.instagram&&['📷','Instagram',safeUrl(p.instagram)],
  p.carta&&['📋','Carta',safeUrl(p.carta)],p.reserva&&['📅','Reservar',safeUrl(p.reserva)],p.video&&['▶️','Vídeo',safeUrl(p.video)]
].filter(Boolean);if(!links.length)return '';return `<div class="action-grid">${links.map(([i,l,u])=>`<a href="${esc(u)}" target="${u.startsWith('tel:')?'_self':'_blank'}" rel="noopener"><span>${i}</span>${esc(l)}</a>`).join('')}</div>`}
function mapBlock(p){const parts=String(p.coordenades||'').split(',').map(x=>Number(x.trim()));if(parts.length!==2||!Number.isFinite(parts[0])||!Number.isFinite(parts[1]))return '';const [lat,lon]=parts,d=.008,bbox=[lon-d,lat-d,lon+d,lat+d].join('%2C');const embed=`https://www.openstreetmap.org/export/embed.html?bbox=${bbox}&layer=mapnik&marker=${lat}%2C${lon}`;const open=`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lon}#map=17/${lat}/${lon}`;return `<section class="detail-section"><h3>Ubicació</h3><div class="map-wrap"><iframe src="${embed}" loading="lazy" title="Mapa de ${esc(p.nom)}"></iframe><a href="${open}" target="_blank" rel="noopener">Obrir el mapa gran ↗</a></div></section>`}
function recommendationBlock(p){const names=uniq([p.recomanatPer,...asArray(p.recomanacions).map(r=>r.nom)].filter(Boolean));return names.length?`<div class="recommended"><span>💡 Recomanat per</span><b>${names.map(esc).join(' · ')}</b></div>`:''}
function infoRows(p){const rows=[
 ['📍','Adreça',p.adreca],['🕒','Horari',p.horari],['🚪','Tancament',p.tancament],['ℹ️','Observacions d’horari',p.observacionsHorari],
 ['💶','Preu mitjà',p.preuMitja?`${p.preuMitja} €`:p.rang],['🍽️','Menú',p.menu],['📖','Segon menú',p.menu2],['💶','Preu segon menú',p.preuMenu2?`${p.preuMenu2} €`:'' ],
 ['☎️','Telèfon',cleanPhone(p.telefon1)],['☎️','Segon telèfon',cleanPhone(p.telefon2)]
].filter(([, ,v])=>v!==''&&v!=null);return rows.length?`<section class="detail-section"><h3>Informació pràctica</h3><div class="info-list">${rows.map(([i,l,v])=>`<div><span>${i}</span><p><small>${esc(l)}</small>${esc(v)}</p></div>`).join('')}</div></section>`:''}
function featureBlock(p){const features=uniq([...(p.serveis||[]),p.terrassa?'Terrassa':'',p.senseGluten?'Opcions sense gluten':'',p.vegetaria?'Opcions vegetarianes':''].filter(Boolean));return features.length?`<section class="detail-section"><h3>Serveis i característiques</h3><div class="recipe-stats">${features.map(x=>`<span class="chip">✓ ${esc(x)}</span>`).join('')}</div></section>`:''}
function showPlace(p){const categories=uniq([...(p.cuines||[]),...(p.categories||[]),...(p.especialitats||[])]);return `<div class="eyebrow">${icons[p.tipus]} ${esc(labels[p.tipus]?.[0]||p.tipus)}</div><h2>${esc(p.nom)}</h2><div class="loc">📍 ${esc(loc(p))}</div>${statusNotice(p)}${recommendationBlock(p)}${categories.length?`<div class="recipe-stats">${categories.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>`:''}${actionLinks(p)}${infoRows(p)}${mapBlock(p)}${featureBlock(p)}${p.notes?`<section class="detail-section"><h3>Notes i observacions</h3><div class="detail-text note-box">${esc(p.notes)}</div></section>`:''}${p.tipus==='restaurant'?ratingSummary(p):''}${visits(p)}${gallery(p)}`}
function showDetail(p){if(!p)return;const img=p.imatge||p.logo||p.imatges?.[0]||'';$('#heroimg').style.backgroundImage=img?`url('${img}')`:'none';$('#detailbody').innerHTML=p.tipus==='recepta'?showRecipe(p):showPlace(p);$('#detail').classList.add('open')}
$('#globalSearch').oninput=e=>{const q=e.target.value;$('#clear').classList.toggle('hidden',!q);$('#home').classList.remove('hidden');$('#moduleView').classList.add('hidden');globalSearch(q)};
$('#clear').onclick=()=>{$('#globalSearch').value='';$('#clear').classList.add('hidden');globalSearch('')};
$$('[data-module]').forEach(b=>b.onclick=()=>openModule(b.dataset.module));
$('#filterBtn').onclick=()=>$('#filters').classList.add('open');
$('#filters').onclick=e=>{if(e.target===$('#filters'))$('#filters').classList.remove('open')};
$('#region').onchange=()=>{filters.region=$('#region').value;filters.zone='';populateFilters()};
$('#apply').onclick=()=>{filters.region=$('#region').value;filters.zone=$('#zone').value;filters.cuisine=$('#cuisine').value;filters.specialty=$('#specialty').value;filters.status=$('#status').value;$('#filters').classList.remove('open');renderModule()};
$('#close').onclick=()=>$('#detail').classList.remove('open');
$('#detail').onclick=e=>{if(e.target===$('#detail'))$('#detail').classList.remove('open')};
$$('[data-nav]').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;$$('[data-nav]').forEach(x=>x.classList.toggle('active',x===b));if(n==='home'){$('#home').classList.remove('hidden');$('#moduleView').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}if(n==='search'){$('#home').classList.remove('hidden');$('#moduleView').classList.add('hidden');$('#globalSearch').focus();window.scrollTo({top:0,behavior:'smooth'})}if(n==='favorites')alert('Els preferits comuns quedaran activats en una versió posterior.');if(n==='history')alert('L’historial quedarà activat en una versió posterior.')});
function setGreeting(){const h=new Date().getHours();let text='Bon dia!';if(h>=13&&h<20)text='Bona tarda!';else if(h>=20||h<6)text='Bona nit!';$('#greeting').textContent=text}
setGreeting();counts();

if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js').catch(console.error));
}
